import { Routes, Route } from "react-router-dom"
import Header from "./components/Header"
import Footer from "./components/Footer"
import Home from "./pages/Home"
import About from "./pages/About"
import Programs from "./pages/Programs"
import Campaigns from "./pages/Campaigns"
import Donate from "./pages/Donate"
import Volunteer from "./pages/Volunteer"
import Contact from "./pages/Contact"
import Teams from "./pages/Teams"
import TeamGroup from "./pages/TeamGroup"
import ResourcePage from "./pages/ResourcePage"
import AboutSubpage from "./pages/AboutSubpage"
import Events from "./pages/Events"
import NotFound from "./pages/NotFound"
import AdminLayout from "./pages/admin/AdminLayout"
import AdminDashboard from "./pages/admin/AdminDashboard"
import AdminDonors from "./pages/admin/AdminDonors"
import AdminVolunteers from "./pages/admin/AdminVolunteers"
import AdminGallery from "./pages/admin/AdminGallery"
import AdminReports from "./pages/admin/AdminReports"
import AdminLogin from "./pages/admin/AdminLogin"
import VolunteerLogin from "./pages/volunteer/VolunteerLogin"
import VolunteerUpdates from "./pages/volunteer/VolunteerUpdates"
export default function App(){return <div className="flex min-h-screen flex-col bg-background"><Routes><Route path="/admin/login" element={<AdminLogin/>}/><Route path="/admin" element={<AdminLayout/>}><Route index element={<AdminDashboard/>}/><Route path="donors" element={<AdminDonors/>}/><Route path="volunteers" element={<AdminVolunteers/>}/><Route path="gallery" element={<AdminGallery/>}/><Route path="reports" element={<AdminReports/>}</Route><Route path="/*" element={<><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/about/leadership" element={<AboutSubpage/>}/><Route path="/about/legal-terms" element={<AboutSubpage/>}/><Route path="/about/reports" element={<ResourcePage/>}/><Route path="/about/reports/:type" element={<ResourcePage/>}/><Route path="/about/certificates/:type" element={<ResourcePage/>}/><Route path="/resources/photos" element={<ResourcePage/>}/><Route path="/resources/videos" element={<ResourcePage/>}/><Route path="/resources/achievements-awards" element={<ResourcePage/>}/><Route path="/resources/press-stories" element={<ResourcePage/>}/><Route path="/events" element={<Events/>}/><Route path="/programs" element={<Programs/>}/><Route path="/campaigns" element={<Campaigns/>}/><Route path="/teams" element={<Teams/>}/><Route path="/teams/:group" element={<TeamGroup/>}/><Route path="/donate" element={<Donate/>}/><Route path="/volunteer" element={<Volunteer/>}/><Route path="/volunteer/login" element={<VolunteerLogin/>}/><Route path="/volunteer/updates" element={<VolunteerUpdates/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes><Footer/></>}/></Routes></div>}
